version: "3.9"
services:
  mongo-database:
    container_name: mongodb
    image: mongo:7.0.0-rc7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_DATABASE=quotesdb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dev
      - ME_CONFIG_MONGODB_SERVER=mongo-database
    depends_on:
      - mongo-database
    restart: unless-stopped
    ports:
      - "8888:8081"